name: RAS
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  fluentui_system_icons: ^1.1.273
  iconsax_plus: ^1.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.5.3
  web: ^1.1.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  cinetpay: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/kanjad.png
    - assets/images/AG.png
    - assets/images/BG.png
    - assets/images/RG.png
    - assets/images/PG2.png
    - assets/images/EG2.png
  uses-material-design: true
