// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuY__1KmvmRVUEnZ-j60mLV4foPWaLLBE',
    appId: '1:57697834839:web:10a2b652eb8f054cb89012',
    messagingSenderId: '57697834839',
    projectId: 'royal-advance-services',
    authDomain: 'royal-advance-services.firebaseapp.com',
    storageBucket: 'royal-advance-services.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgCZ-VqQ-fVDiI9s6fMf7ZZGw7sbcAJo',
    appId: '1:57697834839:android:0ba1bc1fed42861fb89012',
    messagingSenderId: '57697834839',
    projectId: 'royal-advance-services',
    storageBucket: 'royal-advance-services.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuY__1KmvmRVUEnZ-j60mLV4foPWaLLBE',
    appId: '1:57697834839:web:c06a221cb76634c1b89012',
    messagingSenderId: '57697834839',
    projectId: 'royal-advance-services',
    authDomain: 'royal-advance-services.firebaseapp.com',
    storageBucket: 'royal-advance-services.firebasestorage.app',
  );
}
